### ISSUE TITLE
Hotswap + alternate MCU?

### ISSUE THREAD

**Issue by bnorick** [swift502/Krtkus#3]
I love the design, great work! A couple things that would really take it over the top for me, namely the ability to use hotswap sockets and the ability to make it wireless. I'd love to use a Seeed XIAO BLE (like TOTEM) along with two daisy chained shift registers (74hc595) which would be needed in order to get enough pins for the matrix.

I know there are a lot of learning resources available in this space and I started to have a look at them in order to work on this project, but before I went further into the rabbit hole I wanted to get your opinion. Is this a fools errant?  Have you already considered and/or started on any changes like these? Any other input?

Thanks!

**Comment by swift502** [comment]
Hi! Glad you like the board. 👌

1. I originally wanted hot swap, because I thought I could get JLCPCB to solder them for me. But that's very impractical, so I just ditched hotswap altogether, because it would just mean spending extra money on the sockets.
But obviously it's possible, just needs rewiring of the pcb. I would do that if there was more interest. But right now you'd have to do that yourself. In kicad.

2. As for the controller, that sounds a little advanced for me. I don't know anything about daisy chaining and stuff. You'll have to redesign the whole PCB, and rebuild the qmk firmware - change the controller type and cols/rows pin identifiers.
So it's possible but those are very extensive changes. You'd almost be better off starting from scratch, because you'd be rewiring the whole PCB.

**Comment by swift502** [comment]
Feel free to reopen if you have any more questions. 👌
